### ISSUE TITLE
Вывод значения из одного определённого доп. поля

### ISSUE THREAD

**Issue by 4iLi737** [dle-modules/DLE-BlockPro#102]
Здравствуйте,

модуль понравился, но я никак не пойму, как в шаблоне написать, чтоб модуль выводил мне с одного определённого доп. поля значение, если оно там есть.

Тоесть, модуль находит новости которые надо, есть доп поле, в котором внесены цифры, найдя 10 новостей например нужно вывести все значения из определённого поля в таком виде 69, 87, 90 итд. только цыфры через запятую.

**Comment by pafnuty** [comment]
Добрый вечер.
Посмотрите как организован вывод допполей в шаблонах, идущих в комплекте с модулем, 
почитайте [документацию](http://bp.pafnuty.name/documentation/#el-xfields), посмотрите различные [примеры реализации](http://bp.pafnuty.name/examples/)
