### ISSUE TITLE
проблема с датой

### ISSUE THREAD

**Issue by niceshot007** [dle-modules/DLE-BlockPro#103]
Использую блокпро для вывода новостей сайта, дата новостей вчера, сегодня, завтра
сегодня 30 число завтра первое и дату не распознает, и пишет просто цифрами а в другие дни все нормально, как можно решить данную проблему?

{include file="engine/modules/base/blockpro.php?template=list&limit=100&day=1&dayCount=1&sort=date&order=old&future=y&allowMain=only&catId=this"}

} elseif (date('Ymd', $date) == date('Ymd') +1) {
$showDate = $lang['time_tomorrow'] . langdate('', $date);

**Comment by pafnuty** [comment]
Вероятно так происходит потому, что в языковом файле нет значения для ключа `time_tomorrow`

**Comment by niceshot007** [comment]
// 6.5
'time_tomorrow'		=>	"<div class=red1><b>ЗАВТРА</b></div>",

**Comment by pafnuty** [comment]
https://dle-news.ru/demo.html
website.lng:
![image](https://user-images.githubusercontent.com/1635679/33449419-2630aacc-d622-11e7-9628-8fcc9d8e9a4c.png)

Вероятно ваша версия DLE модифицирована или пиратская.

Тем не менее, попробуйте вывести в браузер обе части условия проверки
`date('Ymd', $date)` и `date('Ymd') +1` ну и переменную `$date` заодно т.к. у меня есть подозрение, что файлы модуля так же изменены, если это так, вам придётся разбираться с вашим кодом самостоятельно. После чего, кстати, вы можете отправить PR в этот репозитоий и тем самым улучшить модуль.

**Comment by niceshot007** [comment]
изменен

if (date('Ymd', $date) == date('Ymd')) {
			$showDate = $lang['time_heute'] . langdate('', $date);
			
		} elseif (date('Ymd', $date) == date('Ymd') - 1) {
			$showDate = $lang['time_gestern'] . langdate('', $date);
			
		} elseif (date('Ymd', $date) == date('Ymd')  +1) {
			$showDate = $lang['time_tomorrow'] . langdate('', $date);

**Comment by pafnuty** [comment]
`(date('Ymd', $date) == date('Ymd')  +1)` попробуйте заенить на 
`(date('Ymd', $date) == date('Ymd')  + $_TIME + 86400)` как вариант

**Comment by niceshot007** [comment]
также

**Comment by pafnuty** [comment]
Тогда https://github.com/dle-modules/DLE-BlockPro/issues/103#issuecomment-348288168

**Comment by niceshot007** [comment]
а если бы сегодня было бы 01.12.2017 то показывает так как надо, все правильно
