### ISSUE TITLE
Проблема с датой

### ISSUE THREAD

**Issue by niceshot007** [dle-modules/DLE-BlockPro#104]
Здравствуйте, использую модуль для вывода новостей, дата стоит вчера сегодня завтра, а далие уже по числам, но в конце месяца оно уже не пишет завтра оно просто пишет 01.12.2017 как можно исправить данную проблему?
{include file="engine/modules/base/blockpro.php?template=list&limit=100&day=1&dayCount=1&sort=date&order=old&future=y&allowMain=only&catId=this"}

} elseif (date('Ymd', $date) == date('Ymd')  +1) {
			$showDate = $lang['time_tomorrow'] . langdate('', $date);

**Comment by pafnuty** [comment]
Дубль #103
