### ISSUE TITLE
title блока

### ISSUE THREAD

**Issue by niceshot007** [dle-modules/DLE-BlockPro#105]
blockpro выводит новости у меня на сайте по дням вчера сегодня и т.д,
То есть, Блок 1 "Новости за сегодня" и список новостей, как можно сделать чтоб titl блока уберался если в блоке нет новостей?

**Comment by niceshot007** [comment]
???

**Comment by pafnuty** [comment]
@niceshot007 достаточно просто создать условие в шаблоне:
```tpl
{var $newsCount = $list|count}
{if $newsCount > 0}
    Новости есть
{/if}
```
