### ISSUE TITLE
memcached

### ISSUE THREAD

**Issue by tidzh** [dle-modules/DLE-BlockPro#108]
Добрый день, а можно в будущий обновления, если такие планируется, плотнее поработать над интеграцией с memcached. Например, со временем жизнью кеша в памяти. #

**Comment by pafnuty** [comment]
@tidzh Старые версии DLE не поддерживают подобный функционал, поэтому не уверен, что это требуется, но попробую реализовать для новых версий.

**Comment by pafnuty** [comment]
@tidzh В свежих версиях DLE (13, если не ошибаюсь) можно задать в настройках параметр `clear_cache`. Это решит проблему.
