### ISSUE TITLE
Совместимость с DLE 13.0

### ISSUE THREAD

**Issue by pafnuty** [dle-modules/DLE-BlockPro#113]

**Comment by ballios** [comment]
Вы хотите сказать, что BlockPro 5.0.2 не работает нормально с DLE 13.x ?

**Comment by pafnuty** [comment]
@ballios я не проверял, но теоретически могут возникнуть проблемы с постраничной навигацией и прочими ajax вызовами модуля.
P.S. не в том репозитории лейбл сменил, пардон.

**Comment by ballios** [comment]
Так это придется на свой страх и риск теперь ставить BlockPro 5.0.2 на DLE 13.x ?
А когда оперативно можно ждать 6-й версии, чтобы не иметь проблем на DLE 13.x ?

**Comment by pafnuty** [comment]
@ballios поставьте локально DLE 13, у меня физически пока нет возможности это сделать 😞.
Используйте OpenServer для удобства.

**Comment by ballios** [comment]
У меня также нет возможности тестить локально, жаль будет, если BlockPro 5.0.2 не работает нормально на DLE 13.x

**Comment by smart-ex** [comment]
@ballios Я буду скоро проверять у себя, отпишусь тут.

**Comment by Yuribtr** [comment]
Буду тоже проверять у себя на 13-й версии, отпишусь. 
Вопрос: чтобы не делать новую инсталляшку возможно ли поставить два блокпро рядом?

**Comment by pafnuty** [comment]
@smart-ex  скиньте строки подключения сюда, возможно что-то не оптимально выбирается.
@Yuribtr Теоретически да, но возможно надо будет много внутри переименовать.

**Comment by Yuribtr** [comment]
@pafnuty на всякий случай сообщаю что ваш сайт **bp.pafnuty.name** с европейских IP не открывается.

**Comment by pafnuty** [comment]
Роскомнадзор добрался до голов европейских чиновников? О_о

пн, 4 июн. 2018 г., 0:09 Yuri <notifications@github.com>:

**Comment by smart-ex** [comment]
@pafnuty да вроде тут все просто)
 `{include file="engine/modules/base/blockpro.php?template=bp_box&cacheLive=10&limit=2&catId=6,5,12"}`
`{include file="engine/modules/base/blockpro.php?template=bp_box&cacheLive=10&startFrom=3&limit=2&catId=6,5,12"}`
`{include file="engine/modules/base/blockpro.php?template=bp_strip&cacheLive=10&limit=4&catId=7"}`
`{include file="engine/modules/base/blockpro.php?template=bp_big&cacheLive=10&limit=2&catId=49"}`
`{include file="engine/modules/base/blockpro.php?template=bp_box&cacheLive=10&limit=4&catId=8"}`
`{include file="engine/modules/base/blockpro.php?template=bp_big&cacheLive=10&limit=4&catId=51,52"}
`
тоже самое на длешном {custom} работает без проблем

**Comment by pafnuty** [comment]
@smart-ex Возможные проблемы: 
1) большая БД и много групп
2) Используется memcache (cacheLive с ним не работает)
3) Что-то не то с модулем в связке с 13 версией.

**Comment by smart-ex** [comment]
@pafnuty да, дело было в кэше. Упустил момент что bp не работает с memcache (

**Comment by pafnuty** [comment]
@smart-ex кстати, в новых версиях DLE появилась возможность указывать время жизни кеша, вполне вероятно, что может получиться реализовать работу с мемкешем https://github.com/dle-modules/DLE-BlockPro/issues/108

**Comment by pafnuty** [comment]
2eea89d47989448c2168b8dfb3cec7ca899c5a6a
