### ISSUE TITLE
не корректная работа xfSearch

### ISSUE THREAD

**Issue by smart-ex** [dle-modules/DLE-BlockPro#115]
# Описание ошибки:
При использовании параметра xfSearch вывод будет некорректный,
```php
{include file="engine/modules/base/blockpro.php?xfSearch=name|value&showstat=y"}
```
 так как параметр `name|value` в коде `str_replace('|', '|%', $xf)`  преобразуется в условия для запроса 
`(p.xfields LIKE '%name|%value%')` такой запрос вернет совпадение по строкам 'name|'  и 'value', а не то что ожидается 'name=value'

**Comment by pafnuty** [comment]
@smart-ex Так сделано, потому что иначе не будет работать фильтрация,описанная в этом тиккете https://github.com/dle-modules/DLE-BlockPro/issues/69
Попробуйте включить экспериментальные функции и перенести допполя в отдельную таблицу (в DLE 11.3 такая возможность появилась, если не ошибаюсь)
