### ISSUE TITLE
Обращение 896-885448 Не работает thisNewsTags

### ISSUE THREAD

**Issue by pafnuty** [dle-modules/DLE-BlockPro#116]
Здравствуйте,
в полной новости пытаюсь получить похожие новости с такими же тегами, пишу такую строку:
`{include file="engine/modules/base/blockpro.php?template=blockpro/related_news_fullstory&fixed=ignore&nocache=y&limit=5&sort=date&day=300&tags=thisNewsTags&showstat=y"}
`
В итоге получаю все подряд, а первым запросом в отладчике идет:
`SELECT news_id FROM `dle_tags` WHERE tag regexp "[[::]]"`

Выходит что служебное слово thisNewsTags не подменяется автоматически на теги просматриваемой полной новости. При том, что не помогает доавбление в строку `&related={news-id} `

Но если указывать теги в явном виде, например `&tags=сирия,зерно`
то запрос выполняется правильно:
`SELECT news_id FROM `dle_tags` WHERE tag regexp "[[:сирия,зерно:]]" `

По документации для использования `thisNewsTags `никаких ограничений нет. В чем может быть проблема? Проблема проявляется на версии 4.9.1 и 5.0.2.

Заранее благодарен!

**Comment by Yuribtr** [comment]
Дополнение к сообщению выше:
Версия DLE 13.0, тип используемого ЧПУ - 3
