### ISSUE TITLE
Вывод компаний

### ISSUE THREAD

**Issue by never3d22** [dle-modules/DLE-BlockPro#117]
Подскажите пожалуйста как вывести компании с галочками  если новость принадлежит категориям что в заголовке таблицы. Если нет новости в категории, галочку не ставить, если есть, ставить. Вот пример
http://pokupatel.pro/dom/bytovaya-tehnika/

**Comment by pafnuty** [comment]
Как то так примерно: 
```smarty
	{foreach $list as $el}
		{set $catName = $el.category|catinfo:'name'}
		{if $catName == 'имя_в_шапке'}
			устанавливаем галочку
		{/if}
	{/foreach}	
```
