### ISSUE TITLE
Объединение результатов нескольких запросов

### ISSUE THREAD

**Issue by Yuribtr** [dle-modules/DLE-BlockPro#118]
Возможно ли объединить результаты вывода двух (или более запросов) в одном шаблоне, чтобы обрабатывать их как один массив?

Задача: построение списка новостей, чередующихся из разных категорий (обычные новости и реклама). 
Но из рекламных категорий нужно выбрать ВСЕ удовлетворяющие критерию новости (по доп.полю), а с обычных новостных категорий  нужно выбрать не более скажем 20 новостей (или на 1 единицу больше чем вернет первый запрос рекламы) и у новостей будут другие критерии отборки.

Сейчас это все делается двумя includ'ами и упорядочивается на стороне клиента в JS.

**Comment by pafnuty** [comment]
Объединить врядли получится, но вот избавиться от лишних действий на js думаю можно.
Что-то типа такого у вас будет в шаблоне:
суть в том, что бы "добрать" недостающие новости, если такие есть и положить их в общий массив со всеми новостями, которые уже в выборке.

```smarty

{set $maxNewsCount = 10}

{if $count > 0 && $count < $maxNewsCount}
	
	{set $count = $list|count}
	{set $x = $maxNewsCount - $count }

	{*
		Получаем новости прямым запросом в БД, через класс SafeMySQL
		http://phpfaq.ru/safemysql
	*}

	{set $restNews = $.blockPro->db->getAll('SELECT * FROM ?n LIMIT 0, ?i', 'dle_post', $x)}
	{foreach $restNews as $restEl}
		{add $list[] = $restEl}
	{/foreach}
{/if}
{foreach $list as $el}
	<pre>{$el|dump}</pre>
{/foreach}	
```
Ну и параметры запроса в БД надо под себя подобрать.

**Comment by Yuribtr** [comment]
Круто, а я и не подозревал что так можно в шаблоне обращаться еще раз к БД. 
На данный момент у меня есть временное решение -  я выбираю все новости из категорий одним запросом по всем нужным критериям (получая избыточное количество), а потом в шаблоне, в цикле выбираю нужные и компоную из них новый список с нужным мне порядком. 
Но это съедает достаточно много памяти (около 3 тысяч записей возвращается) и вот статистика:

> [10 время:] 0,15468120574951
> Время выполнения запросов: 0,48679971694946
> Время выполнения скрипта: 0,236277 c.
> Расход памяти: 66,81Мб 

Так что, думаю если воспользоваться вашим подходом я сильно облегчу серверу задачу!

**Comment by Yuribtr** [comment]
Все получилось даже лучше чем ожидалось. Пришлось немного обработать xfields. Полный текст шаблона если кому интересно можно глянуть здесь: https://pastebin.com/iPLtEv8E

Статистика выполнения блока просто доставляет ))))
> [12 время:] 0,0019049644470215
> Время выполнения запросов: 0,34853982925415
> Время выполнения скрипта: 0,111172 c.
> Расход памяти: 2,49Мб

**Comment by pafnuty** [comment]
@Yuribtr `$el.xfields` должен содержать массив
https://github.com/dle-modules/DLE-BlockPro/blob/358d9932fcfb56cb4fcd36b588198e052540689d/engine/modules/base/blockpro.php#L983
