### ISSUE TITLE
Важный вопрос: Сортировка по дате + авто-удаление картинок

### ISSUE THREAD

**Issue by ballios** [dle-modules/DLE-BlockPro#122]
Нужно:
`{include file="engine/modules/base/blockpro.php?template=blockpro/myshab&limit=6&notPostId=this&sort=date"}`

В шаблоне указаны размеры картинок.
Запросы блока начинают работать, создается папка для картинок.

**Вопрос такой:**
- исходя из потребности в 6 картинках в блоке, отсортированных по дате, каждый раз при добавлении новых 6 новостей с картинками, будут ли старые (теперь совершенно ненужные) картинки авто-удаляться со своей рабочей папки на сервере, или же так и будет всё складироваться до ручного удаления?

**Comment by pafnuty** [comment]
@ballios Автоудаления картинок в модуле нет, поэтому они будут сохраняться до ручного удаления.
