### ISSUE TITLE
Реализация улучшенного поиска похожих новостей из dle13.1

### ISSUE THREAD

**Issue by ballios** [dle-modules/DLE-BlockPro#123]
Будете ли вы обновлять DLE-BlockPro сразу после выхода DLE 13.1 ?
Дело в том, что там 37 пунктом внедрено такое:

- Улучшен поиск **похожих новостей на сайте**. Показ похожих новостей стал более релевантным по сортировки найденных публикаций.

А насколько я знаю, BlockPro до сих пор использует такие же алгоритмы как у основного движка?

**Comment by pafnuty** [comment]
@ballios да, это было бы неплохо т.к. сейчас похожие новости — достаточно тяжёлая штука.

**Comment by ballios** [comment]
Вышла DLE 13.1.
Обновите пожалуйста алгоритмы подбора похожих постов и для BlockPro, как новой DLE.
Есть надежда, что этот механизм действительно станет лучше!

**Comment by pafnuty** [comment]
Да, судя по виду улучшения есть.
![image](https://user-images.githubusercontent.com/1635679/46372045-12a78880-c69b-11e8-9701-f19d5037e407.png)

**Comment by ballios** [comment]
> Да, судя по виду улучшения есть.
> ![image](https://user-images.githubusercontent.com/1635679/46372045-12a78880-c69b-11e8-9701-f19d5037e407.png)

Когда планируете порадовать пользователей новой версией? ))

**Comment by ballios** [comment]
5.1 WIP - это нужно вручную внести в версию 5.0.2 ?
Или же 5.1 - грядет?

**Comment by pafnuty** [comment]
@ballios Готово, структуру запроса привёл в соответсвие с DLE13, но не проверял т.к. нет БД подходящего размера.
