### ISSUE TITLE
Ошибка базы данных 

### ISSUE THREAD

**Issue by steamn** [dle-modules/DLE-BlockPro#124]
#Update: Проблема была в базе данных, таблицы которой были сильно изменены сторонними модулями. BlockPro работает отлично. 

# Описание ошибки:

MySQL error in file: /engine/classes/mysql.php at line 53
Error Number: 1
MySQL Error! 
The Error returned was: Too many connections

В конфиге - max connections = 400 (не знаю, много это или мало, по умолчанию было 150)

- При каких условиях воспроизводится ошибка
При вставке  строки подключения в шаблон 

- Страница, на которой наблюдается ошибка
- Вносились ли модификации в движок
- Версия DLE: 10.3
- Версия PHP: 7.2.8

## Строка подключения с включенным параметром showstat:

```php
{include file="engine/modules/base/blockpro.php?template=blockpro/list&limit=5&catId=2"}
```

## Статистика генерации:
_Содержимое блока в красной рамке в конце блока с новостями_

```sql
Запрос(ы): 

недоступно
```

## Код используемого шаблона:
```tpl
{*
    $block_id - это уникальный идентификатор блока (у блоков с разными настройками он разный) для того, что бы правильно организовать постраничную навигацию на ajax.
*}
<div id="{$block_id}">
    {$pages}
    {*
        Тут мы определяем количество новостей в блоке
        $list - переменная, содержащая массив с новостями.
    *}
    {var $newsCount = $list|length}
    В блоке {$newsCount} {$newsCount|declination:'новост|ь|и|ей'}
    {*Пробегаем по массиву с новостями*}
    {foreach $list as $key => $el}
        <div class="content content-border-bottom">
            <div class="col col-mb-12">
                рейтинг: {$el.showRating} {$el.showRatingCount}
                <h3>
                    {$el.favorites}[{$el.id}] <a href="{$el.url}">{$el.title}</a> {if $el.allow_edit} <a href="#" {$el.editOnclick}>[редактировать]</a> {/if}
                </h3>
                <img src="{$el.avatar}" alt="{$el.name}" width="46">
                {$el.category|catinfo:'name'} | {$el.category|catinfo:'url'} | {$el.date|dateformat} | {$el.date|dateformat:"d F Y"}
                в новости: {$el.short_story|length} симв.
            </div>
        </div>
        {if $key == 1}
            <div class="content content-border-bottom">
                <div class="col col-mb-12">
                    <h4>Выводим навигацию между новостями</h4>
                    {$pages}
                </div>
            </div>
        {/if}
    {foreachelse}
        {*Если новостей нет - выведем информацию об этом*}
        <p>Новостей нет</p>
    {/foreach}

</div> <!-- #{$block_id} -->
```

**Comment by pafnuty** [comment]
@steamn скорее всего сервер просто не справляется с нагрузкой.

**Comment by steamn** [comment]
> @steamn скорее всего сервер просто не справляется с нагрузкой.

CMS установлена на выделенном сервере с восьмиядерном Xeon W3520 и 16Гб памяти

**Comment by pafnuty** [comment]
@steamn под нагрузкой я имел ввиду количество соединений с сервером БД.
Если у вас UNIX система, можно ставить в конфиге до 1000.

Как будет время я проверю модуль, возможно в нём есть ошибка, которая не завершает коннект к БД по завершению работы.

**Comment by steamn** [comment]
> @steamn под нагрузкой я имел ввиду количество соединений с сервером БД.
> Если у вас UNIX система, можно ставить в конфиге до 1000.
> 
> Как будет время я проверю модуль, возможно в нём есть ошибка, которая не завершает коннект к БД по завершению работы.

Увеличил max connections до 990 и получил: 
> 504 Gateway Time-out

в error.log это: 
> [error] 1640#1640: *1218 upstream timed out (110: Connection timed out)

**Comment by lazyphpdev** [comment]
@steamn Вас не смущает что поддержка PHP 7.2.x добавилась только в DLE версии 13.0 ? А у вас 10.3.

**Comment by steamn** [comment]
> @steamn Вас не смущает что поддержка PHP 7.2.x добавилась только в DLE версии 13.0 ? А у вас 10.3.
Версия DLE конечно же 13-я, моя ошибка. Сайт был обновлен с 10.3.
