### ISSUE TITLE
Виджет не учитывает шаблоны пользователей

### ISSUE THREAD

**Issue by Yuribtr** [dle-modules/DLE-BlockPro#127]
Здравствуйте,
спасибо за замечательный модуль, но есть несколько вопросов:

1. При выводе виджета, используется шаблон пользователя, кто первым запросил его содержимое.
Скажем на сайте есть два шаблона "Шаблон1" (по умолчанию) и "Шаблон2" выбран для Администратора. 
Строка поключения виджета такая:
`{include file="engine/modules/base/blockpro.php?template=blockpro/banners_right_20s&cacheLive=20s&limit=14&catId=10&sort=randomLight"}`
В каждой папке шаблонов есть свой файл blockpro/banners_right_20s.tpl

Если сразу после создания виджета сначала Гость запрашивает строку виджета (https://example.com/blockpro.php?block=bp1223345413), то оформление статей будет взято из его шаблона "Шаблон1". Даже Администратору с другим шаблоном будет показываться оформление Гостя. И наоборот, если Администратор успел первым запросить виджет, то Гостю будет показано содержимое выбранного шаблона Администратора.

Речь идет только об оформлении из шаблона. Содержимое же показывается разное.

Если же в шаблоне по умолчанию будет отсутствовать файл banners_right_20s.tpl, то Администратору выведется пустой блок. Возможно так спроектировано, но это странно и неудобно. 

Название шаблона dle_skin передается через Cookies
Версия DLE: 13.0
Версия BlockPro: 5.0.2
Версия PHP: 7.2
Модификаций движка модуля не было.
--------------------------------------------------------------------------------
2. И еще вопрос, как видно в строке подключения нет showstat=y, но виджет все равно выводит в консоль время своей генерации. Как это отключить?
` [blockpro]: id: bp1223345413, time: 0.09249 s.`
--------------------------------------------------------------------------------
3. Было бы классно сделать возможность изменения виджета, вместо создания нового.
--------------------------------------------------------------------------------
4. Было бы классно, иметь возможность самому менять код обновления виджета.

**Comment by pafnuty** [comment]
@Yuribtr
1. Действительно странное поведение.
Вот тут https://github.com/dle-modules/DLE-BlockPro/blob/2eea89d47989448c2168b8dfb3cec7ca899c5a6a/engine/modules/base/blockpro.php#L262 определяется шаблон, который необходимо взять как текущий шаблон сайта (в т.ч. по кукам). 
Вы проверяли вариант со строкой подключения, а не виджетом? Вполне вероятно, что при использовании модуля через виджет теряется кука.

2. https://github.com/dle-modules/DLE-BlockPro/blob/2eea89d47989448c2168b8dfb3cec7ca899c5a6a/blockpro.php#L139 этой переменной нужно поставить пустое значение `$consoleLog = '';`

3. Когда разрабатывались виджеты, они задумывались как простейший способ вывода новостей на стороних сайтах, поэтому редактирование не предусмотрено. Подумаю над этим.

4. Не совсем понимаю что вы имеете ввиду.

**Comment by Yuribtr** [comment]
>   Вы проверяли вариант со строкой подключения, а не виджетом? Вполне вероятно, что при использовании модуля через виджет теряется кука.

После указанной Вами строки №262 я вставил:
`$consoleLog = 'console.log(\'Current Skin detected: ' . $currentSiteSkin . ' \');';`
И в консоли выводится просто: 
> Current Skin detected:  
Выходит что кука просто не доходит от виджета. Более того, она не определяется и в blockpro.php, который находится в корневом каталоге.
Эта строчка кода не работает:
`$currentSiteSkin = (isset($_COOKIE['dle_skin'])) ? trim(totranslit($_COOKIE['dle_skin'], false, false)) : (isset($_REQUEST['skin'])) ? trim(totranslit($_REQUEST['skin'], false, false)) : $config['skin'];`

**Comment by Yuribtr** [comment]
Все, нашел проблему. В PHP поведение вложенных тренарных операторов отличается от такового в других языках. Вот статья на [эту тему](https://habr.com/post/114899/).
Всего лишь надо вложенный тренарный оператор обернуть в скобки (строка 262):
`$currentSiteSkin = (isset($_COOKIE['dle_skin'])) ? trim(totranslit($_COOKIE['dle_skin'], false, false)) : ((isset($_REQUEST['skin'])) ? trim(totranslit($_REQUEST['skin'], false, false)) : $config['skin']);`

У меня все заработало!

**Comment by Yuribtr** [comment]
>     4\. Не совсем понимаю что вы имеете ввиду.

Все очень просто, если я хочу использовать кастомную анимацию обновления блока, мне нужно получить чистый html код, как он формируется в шаблоне. Тогда я смогу либо в шаблон засунуть свой код с анимацией, либо в колбэке $.ajax().done() сделать свою анимацию, а также какую либо обработку данных (например изменение счетчика загруженных/оставшихся новостей).

**Comment by Yuribtr** [comment]
Нашел как получать чистый HTML, надо просто запрашивать blockpro.php?frame=
Моя невнимательность. Так что пункт 3 и 4 первого сообщения неактуальны.

**Comment by pafnuty** [comment]
@Yuribtr перенёс ошибку с тернарным оператором в отдельный тиккет, этот закрываю.
