### ISSUE TITLE
Вставка кода BlockPro внутрь поста и баннеры

### ISSUE THREAD

**Issue by ballios** [dle-modules/DLE-BlockPro#135]
Реализуйте пожалуйста возможность вставки и выполнения кода BlockPro и через баннерную систему DLE, и через просто вставку кода BlockPro внутрь текста поста прямо в редакторе, когда добавляешь публикацию.

Крайне выгодная и полезная штука иметь вывод всяких новостей именно внутри любого поста, как это делается на новостных сайтах!

Но на данный момент BlockPro не работает ни через баннеры в Админке, ни через редакторы при добавлении новостей.

**Comment by pafnuty** [comment]
@ballios Через баннеры можно выводить и сейчас, это немного не очевидно, но достаточно просто: 
создаёте виджет, берёте код выода через js и вставляете в качестве баннера.

Но если вам нужно реализовать более правильный вывод модуля, то я оставлю этот тиккет открытым для реализации в следующих версиях модуля.

**Comment by ballios** [comment]
> Но если вам нужно реализовать более правильный вывод модуля, то я оставлю этот тиккет открытым для реализации в следующих версиях модуля.

Конечно нужно!
Но, как я помню, через скрипт вроде как не позволяет выводить похожие новости, и еще какие-то лимиты есть?

**Comment by ballios** [comment]
Повторюсь, раз уж вы внесли это предложение в "Улучшения".
Хочется получить корректный вывод особенно похожих постов внутри данного поста.
И кстати, когда же всё-таки можно ожидать этих всех масштабных обновлений, я так понимаю - версию 6.0 ?
Сообщите пожалуйста, очень необходимо всё это...

**Comment by pafnuty** [comment]
@ballios Пока реализацию не представляю возможным, а спроса на эту фичу нет.
К сожалению придётся закрыть тиккет.
