### ISSUE TITLE
S-block 2 0 и DLE-BlockPro

### ISSUE THREAD

**Issue by alukart** [dle-modules/DLE-BlockPro#137]
Здравствуйте
Вопрос Создателя DLE-BlockPro

Я думаю вы знаете более ранний модуль S-block 2 0  он намного функциональнее чем ваш но к сожалению он давно не поддерживается и идет только на старых версиях DLE на новых версиях к сожалению не идет.
Я покупал последнюю версию

**Comment by alukart** [comment]
Я покупал последнюю версию S-block 2 0 и она у меня есть в дезенде и взломанна, Я  могу вам ее скинуть - может вы сможете взять из нее решения и больший функционал и сделать DLE-BlockPro более функциональным.

**Comment by pafnuty** [comment]
@alukart 
Из уважения к @San-Dev я точно не собираюсь брать его разработки без разрешения.
Однако, если вы подробно опишите функционал, который необходимо реализовать, то вполне вероятно его появление в новых версиях модуля.

**Comment by San-Dev** [comment]
Данный модуль был заброшен мной года так 4 назад. Открытая версия без привязки доступна для скачивания всем на сайте sblocks.sandev.pro
Не имею абсолютно ничего против, если идеи или решения будут скопированы.

**Comment by alukart** [comment]
> @alukart
> Из уважения к @San-Dev я точно не собираюсь брать его разработки без разрешения.
> Однако, если вы подробно опишите функционал, который необходимо реализовать, то вполне вероятно его появление в новых версиях модуля.

да там описывать замучаешся, S-block 2 0 был сверх  функциональным, к примеру чтобы все блоки делались и редактировались из админки, а блоки встатвлялись не инклудом в в шаблон а переменной типа вот так {переменная}. 


Автор S-block 2 0 не против, может сможете хотябы попробывать оживить S-block 2 0 чтобы он работал на последних версиях DLE ?

**Comment by alukart** [comment]
S-block 2 0 работает до версии 9,8 но я допиливал до 11 версии DLE но уже немного терялся функционал так как в движке уже много чего менялось и запросы и структура менялись сильно а с версией 13 там вообще мясо моих познаний к сожалению уже  хватает (((

**Comment by pafnuty** [comment]
> да там описывать замучаешся, S-block 2 0 был сверх функциональным

Именно поэтому я и прошу описать то, что требуется реализовать.

**Comment by alukart** [comment]
> > да там описывать замучаешся, S-block 2 0 был сверх функциональным
> 
> Именно поэтому я и прошу описать то, что требуется реализовать.

сделать в админке чтобы был список всех блоков и блоки можно было редактировать из админки а вшаблоне была переменная и не лазить в него постоянно как только меняешь блок.

**Comment by pafnuty** [comment]
Всё это вы можете сделать сейчас, используя виджеты.
Виджет сохраняет строку подключения и вы можете редактровать её под себя. 
Не вижу смысл реализоввывать функционал переменных для шаблона.

**Comment by alukart** [comment]
> Всё это вы можете сделать сейчас, используя виджеты.
> Виджет сохраняет строку подключения и вы можете редактровать её под себя.
> Не вижу смысл реализоввывать функционал переменных для шаблона.

можете сделать S-block 2 0 сделать совместимым с DLE 13?

**Comment by pafnuty** [comment]
@alukart C этим вопросом лучше обратиться в @San-Dev
