### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by panqqq** [dle-modules/DLE-BlockPro#138]
# Описание ошибки:

- Когда ставлю код для появления блока
- Главная страница
Пишет Fatal error: require_once(): Failed opening required '/home/panqnews/zutter/engine/modules/base/core/Fenom.php' (include_path='.:/usr/share/php') in /home/panqnews/zutter/engine/modules/base/core/base.php on line 22

Предпросмотр блока: тут ничего не показывает
- Да,установлен модуль Kylshop
- Версия DLE: 12
- Версия PHP: 7.1.23-2+0~20181017082622.9+stretch~1.gbpab65a0

## Строка подключения с включенным параметром showstat:

```php
{include file="engine/modules/base/blockpro.php?nocache=y&catId=9,10,11"}
```

```sql
Запрос(ы): 
 MySQL вернула пустой результат (т.е. ноль строк). (Запрос занял 0.0003 сек.)
SELECT * FROM `dle_blockpro_blocks`
```

## Код используемого шаблона:
Тут незнаю откуда взять

**Comment by pafnuty** [comment]
@panqqq возможно не хватает прав?

**Comment by panqqq** [comment]
@pafnuty можете помочь с этим?

**Comment by pafnuty** [comment]
@panqqq просто проверьте права и пользователя, которому принадлежат файлы модуля.
Часто бывает так, что php выполняется от другого пользователя, нежели владелец файлов и из-за этого происходят подобные ошибки.
Так же проверьте есть ли указанные файлы в папке.
