### ISSUE TITLE
Обновление на BlockPro 5.1.1

### ISSUE THREAD

**Issue by ballios** [dle-modules/DLE-BlockPro#140]
После обновления на BlockPro 5.1.1, в админке всё равно показывает:
BlockPro (5.1.0)

Вы все файлы в дистрибутиве обновили?

**Comment by pafnuty** [comment]
@ballios да, действительно не все файлы обновлены.
Поправлю в следующем релизе, спасибо за замечание.

**Comment by ballios** [comment]
> не все файлы обновлены...
Но на нормальной работе модуля это не отражается сейчас, я надеюсь?

**Comment by pafnuty** [comment]
@ballios нет, не отразится т.к. версия модуля, это последнее, что изменяется перед выкаткой релиза, иногда я забываю это сделать, а автоматизировать процесс никак не собирусь :)
