### ISSUE TITLE
Навигация в блоке

### ISSUE THREAD

**Issue by nelson-portable** [dle-modules/DLE-BlockPro#141]
Здравствуйте. Как закрыть от индексации страницы навигации в блоке? Там к адресу добавляется "?bid=bpa...".

**Comment by pafnuty** [comment]
@nelson-portable 
Закрытие таких страниц ни чем не отличается от закрытия других, но если вам не принципиально наличие хвостов в URL, можно просто использовать файл blockpro.js вместо blockpro_new.js
