### ISSUE TITLE
При переключении шаблона не сразу обновляется содержимое блоков

### ISSUE THREAD

**Issue by Yuribtr** [dle-modules/DLE-BlockPro#142]
Здравствуйте,
постоянно наблюдаю такое странное поведение. На сайте используется несколько сквозных блоков BlockPro для вывода рекламы. Также вся главная страница строится на выводе двух блоков новостей (главные новости + лента) через BlockPro. 
При переключении дизайна с первого раза не подключаются блоки с выбранного шаблона, в результате чего я вижу дизайн и оформление блоков с прежнего шаблона. А если в прежнем шаблоне отсуствуют таковые, то мне выдается ошибка типа:
"Template blockpro/mainpage_topnews.tpl not found"
Но что интересно, эта ошибка возникает только один раз при переключении. Если обновить страницу - все нормально отображается и больше не глючит.

**Comment by pafnuty** [comment]
@Yuribtr 
напишите версию php, версию модуля, тип кеширования и строки подключения модуля, я попробую воспроизвести.

**Comment by Yuribtr** [comment]
Большое спасибо за ответ!

PHP 7.2
DLE 13.0
тип кеширования "файловый кеш"

Строки подключения блоков, у которых наблюдаются глюки такие:
`{include file="engine/modules/base/blockpro.php?template=blockpro/mainpage_item&nocache=y&limit=50&catId=11,12,13,17,18,19,20,21,22,23,24,25,26,27,29,33,34,41&sort=date&fixed=ignore"}`

`{include file="engine/modules/base/blockpro.php?template=blockpro/commercial_headers_item&nocache=y&limit=7&catId=17&sort=date&fixed=ignore"}
`
`{include file="engine/modules/base/blockpro.php?template=blockpro/mainpage_topnews&nocache=y&xfSearch=v-krutilku|Да||v_krutilku|Да&catId=17,30&sort=randomLight"}`

Причем у первых двух блоков просто выдается дизайн с другого шаблона, поскольку файлы blockpro/mainpage_item и blockpro/commercial_headers_item присутствуют в обеих шаблонах. 

А вот третий модуль при переключении на новый шаблон выдает "Template blockpro/mainpage_topnews.tpl not found", видимо потому что у старого шаблона с которого я переключаюсь отсутствует файл blockpro/mainpage_topnews. Я его добавил в новой версии дизайна.

Все бы ничего, если бы мне не стояла задача (временно) поддерживать на сайте два скина, чтобы пользователи в случае глюков смогли самостоятельно переключаться между ними.

**Comment by Yuribtr** [comment]
Святой Кондратий! Оказывается чтобы избавиться от глюков, надо в папках шаблонов иметь разные имена папок с блоками BlockPro! Иначе начинается смешение стилей при переключении и включенном кешировании блоков. Видимо в механизме кеширования не учитывается папка шаблона, откуда загружается блок. Ввиду этого шаблоны BlockPro с одинаковыми именами будут использовать общий кеш.

**Comment by Yuribtr** [comment]
Вобщем путем длительных изысканий удалось обойти этот глюк, в результате чего становится понятным механизм появления глюка. Итак, если у кого-то есть блоки на странице и вы меняете шаблон "на лету", выбирая шаблон из списка (тег DLE {$changeskin}), то вы получаете страницу по POST запросу, в котором отсуствует либо заменена на дефолтную переменная dle_skin.
Чтобы исправить это поведение надо переключаться вручную, отдельным AJAX запросом и сразу же обновляем страницу:

```
<script>
    function skinChange( skin ) {
        ShowLoading('Переключаемся на старый дизайн, подождите...');
        $.post(
            '/index.php',
            { action_skin_change: "yes", skin_name: skin  }
        ).always(function() {
                window.location = window.location.href.split("#")[0];
            }
        );
    }
</script>
```

**Comment by pafnuty** [comment]
@Yuribtr Теперь можно использовать параметр `cacheNameAddon=xxx`
Просто укажите этот параметр разным для разных шаблонов сайта и они должны будут корректно переключаться.
