### ISSUE TITLE
Как правильно фильтровать поле "Переключатель 'Да' или 'Нет' "?

### ISSUE THREAD

**Issue by get-web** [dle-modules/DLE-BlockPro#143]
Не могу разобраться как правильно фильтровать тип поля " Переключатель 'Да' или 'Нет' "

К примеру строка {include file="engine/modules/base/blockpro.php?template=blockpro/short_block&limit=20&xfSearch=addition|Yes&sort=date&catId=1"}

addition это тип поля список, если список в значении Yes, я вывожу данную новость

Но если изменить тип на Переключатель 'Да' или 'Нет' , то значения, как я понимаю 1 и 0 соответственно. Но когда я пытаюсь выводить: {include file="engine/modules/base/blockpro.php?template=blockpro/short_block&limit=20&xfSearch=addition|1&sort=date&catId=1"} то получается какая-то каша, начинают выводятся новости которые имеют значение 0 в addition, но у которых положение 1 вообще в другом поле, и если поставить все значения полей в 0, тогда исчезает, но есть новости которые не исчезают, пробовал делать перестроение и просто добавлять новые новости, все равно что-то не то получается

**Comment by pafnuty** [comment]
@get-web попробуйте использовать параметр experiment=y (при условии, что у вас DLE > 11) это скорее всего решит проблему т.к. в DLE 11 допполя стали храниться в отдельной таблице и выборка должна будет быть более точной.

**Comment by get-web** [comment]
@pafnuty спасибо
