### ISSUE TITLE
blockpro не подхватывает website.lng отредактированный через управление плагинами

### ISSUE THREAD

**Issue by get-web** [dle-modules/DLE-BlockPro#145]
Через управление плагинами заменил:
`'time_heute'		=>	"Сегодня",`
на:
`'time_heute'		=>	"<div class='today'><span>Сегодня</span></div>",`
При стандартном выводе, все работает, но через блокПро нет. Работает только через ручное редактирование файла. Самого blockpro в управлении плагинами нет поэтому через него тоже не сделать. Как можно решить данный вопрос?

**Comment by pafnuty** [comment]
@get-web 
Вариант решения проблемы на уровне шаблона можно посмотреть тут:
https://github.com/dle-modules/DLE-BlockPro/blob/358d9932fcfb56cb4fcd36b588198e052540689d/templates/Default/blockpro/group.tpl#L17

В самом модуле надпись "сегодня" выводится в этой строке:
https://github.com/dle-modules/DLE-BlockPro/blob/de4406c19d4a4959c6a13918e1b2a7a7c27871a8/engine/modules/base/core/base.php#L363

Ещё вариант:
```tpl
{set $newsDate = $el.date|dateformat}
{if $newsDate  == 'Сегодня'}
<div class='today'><span>{$newsDate}</span></div
{else}
{$newsDate}
{/if}
```
