### ISSUE TITLE
Ошибка Fatal error: Cannot redeclare getCatInfo() 

### ISSUE THREAD

**Issue by aluf007** [dle-modules/DLE-BlockPro#146]
При просмотре блока во вкладке "Результат" я получаю вот такую ошибку: 

Fatal error: Cannot redeclare getCatInfo() (previously declared in /var/www/user/data/www/domain.com/engine/modules/functions.php:2210) in /var/www/user/data/www/domain.com/engine/modules/base/core/base.php on line 441

Строка подключения: 
{include file="engine/modules/base/blockpro.php?cacheLive=600&limit=20&catId=35,30,31,32&day=30&dayCount=1&sort=hit"}

Версия DLE: 12.1
Версия PHP: 5.6.36

**Comment by pafnuty** [comment]
@aluf007 У вас установлены какие либо дополнительные модули?

**Comment by pafnuty** [comment]
@aluf007 Поищите функцию с таким именем в других модулях, которые используются в админке.
Так же попробуйте установить модуль на чистую версию DLE.

**Comment by aluf007** [comment]
Не думаю, что я смогу это сделать. А есть еще какое-то решение?

**Comment by pafnuty** [comment]
В оригинальном файле functions.php нет функции getCatInfo? поэтому есть два пути решения: 
1) Определить в результате каких действия там появилась эта функция и переименовать её, не забыв переименовать её ещё и там, где она используется.
2) Переименовать эту функцию в модуле (и во всех местах, где она используется)

**Comment by aluf007** [comment]
1. в файле functions.php, есть эта функция и вот ее код: 

`function getCatInfo($id, $config)
{
    global $cat_info, $PHP_SELF;
    if( $config['allow_alt_url'] ) $catInfo = "<a href=\"" . $config['http_home_url'] . get_url( $id ) . "/\">{$cat_info[$id]['name']}</a>";
    else $catInfo = "<a href=\"$PHP_SELF?do=cat&amp;category={$cat_info[$id]['alt_name']}\">{$cat_info[$id]['name']}</a>";
    return $catInfo;
}`

Я не возьмусь сейчас искать во всех модулях и файлах где используется эту функция. Получается, что модуль не совместим с другими модулями и конфликтует с ними :(

**Comment by Yuribtr** [comment]
Похоже ТС применил хак из этого [источника](https://seopirat.club/threads/kak-ubrat-kategoriju-s-zhanra.991/).

Решение простое. Просто переименуйте в файле "/engine/modules/functions.php" все вызовы getCatInfo в getCatInfo1. Это можно сделать путем простого Поиска и Замены.
Не забудьте сделать копию.

**Comment by aluf007** [comment]
Да, смена имени функции помогло.
