### ISSUE TITLE
Подсчет и вывод кол-ва картинок в статье.

### ISSUE THREAD

**Issue by ssmirenkov** [dle-modules/DLE-BlockPro#148]
Здравствуйте!
Подскажите как можно вывести количество изображений которые есть в посте? И вообще такое возможно реализовать?
Спасибо!

**Comment by Yuribtr** [comment]
Самый простой вариант "в лоб" - пересчитать количество тегов img в $el.short_story, что то типа:
`{$.php.substr_count($el.short_story, '<img');}`

Еще вариант поэкспериментировать с параметром "номер картинки", выставив его в "all", как в примере из документации:
{$el.full_story|image:$noimage:'intext':'all':'150x450':'':'landscape':true:false}
так вы получите на выходе массив картинок, размер которого можно попытаться выяснить через PHP функцию count. Например:
```
{set $img_arr = $el.full_story|image:$noimage:'intext':'all':'150x450':'':'landscape':true:false}
{$.php.count($img_arr)}
```

Весь код выше не тестировался, но логика примерно правильная

**Comment by pafnuty** [comment]
@ssmirenkov Вот готовый пример на случай, если предложенные выше способы не подойдут: http://bp.pafnuty.name/examples/#19f913ba0ff1d78e15fa98ccd7c339b8
