### ISSUE TITLE
Прописать путь для картинок

### ISSUE THREAD

**Issue by ssmirenkov** [dle-modules/DLE-BlockPro#149]
Здравствуйте!
Не могу прописать путь к картинке вида "Y/m/d"

Пробовал разными способами и через {var} и через {set}, в итоге выводится

Делаю {set $datey = $el.date|dateformat:"Y"} в ссылке указывается $datey
Как сделать что бы выводилось значение?

## Код используемого шаблона:

	{var $noimage}
		{$theme}/dleimages/no_image.jpg
	{/var}
	{foreach $list as $el}
		<img class="lazy" src="/uploads/base/loads.gif" data-src="{$el.short_story|image:$noimage:'small':1:'621x500':75:'crop':true:false:'{$el.date|dateformat:"Y"}/{$el.date|dateformat:"m"}/{$el.date|dateformat:"d"}'}" alt="{$el.title}" title="{$el.title}">
	{/foreach}

**Comment by pafnuty** [comment]
@ssmirenkov нужно просто завести переменную, которая будет формировать нужный путь и уже её использовать в параметрах:
```tpl
{set $uploadPath|strip} {* https://github.com/fenom-template/fenom/blob/master/docs/ru/mods/strip.md *}
    {$el.date|dateformat:"Y"}/{$el.date|dateformat:"m"}/{$el.date|dateformat:"d"}
{/set}

{foreach $list as $el}
    <img class="lazy" 
         src="/uploads/base/loads.gif" 
         data-src="{$el.short_story|image:$noimage:'small':1:'621x500':75:'crop':true:false:$uploadPath}" 
         alt="{$el.title}" 
         title="{$el.title}"
         />
{/foreach}
```
