### ISSUE TITLE
Вывод из доп поля с определённым значением

### ISSUE THREAD

**Issue by maksisru** [dle-modules/DLE-BlockPro#157]
Hi!
Нужно вывести в новости похожие новости с таким же значением доп поля 

делал так 
Собственная фильтрация и колонки БД 

Дополнительные колонки, отбираемые из БД   ->     **p.dle_xfsearch, e.tagvalue**
 Собственные условия фильтрации                     ->     **&setFilter=e.tagvalue|gt|e.tagvalue**

не получилось ошибки как можно сделать такое ?

**Comment by pafnuty** [comment]
@maksisru Попробуйте так:
```
&setFilter=e.tagvalue|gt|[xfvalue_x]
```
где `[xfvalue_x]` Значение необходимого допполя.

**Comment by maksisru** [comment]
спасибо. я сделал через custom `{custom xfields="kinopoisk_id|[xfvalue_kinopoisk_id]" template="custom-similar" from="0" limit="20"}` все прекрасно
