### ISSUE TITLE
Помогите создать сортировку и вывод новостей

### ISSUE THREAD

**Issue by vovan905** [dle-modules/DLE-BlockPro#158]
Выводить новости нужно примерно так: https://bankiros.ru/credit-cards, а слева галочками выбирать теги, при нажатии кнопки поиск, выдавать результат - новости, где находятся все теги, указанные галочками. Помогите сделать, скажите сколько стоит такая работа?

**Comment by pafnuty** [comment]
@vovan905 Модуль не предназначен для таких вариантов использования.
Попробуйте поискать модуль сортировки по допполям.
