### ISSUE TITLE
Уменьшенная картинка дополнительного поля

### ISSUE THREAD

**Issue by makey2** [dle-modules/DLE-BlockPro#163]
Здравствуйте!
Если в шаблоне указать src="/uploads/posts/{$el.xfields.kartinka}" выводится изображение, загруженное через дополнительное поле. Но по задумке размеры картинки необходимо сделать меньше и пропорции сделать одинаковыми.
Подключение в таком виде src="/uploads/posts/{$el.xfields.kartinka|image:$noimage:'small':'1':'70x70':'70':'crop':true:true:''} не работает

- Версия DLE: 12
- Версия PHP: 5.6

В версии BlockPro3  в строке подключения указывал ...&image=kartinka&imgSize=70x70&resizeType=crop и это работало корректно, но при переходе на PHP 7.x модуль  BlockPro3 перестает работать поэтому потребовался BlockPro5.
Как подключить в шаблоне картинку уменьшить ее и обрезать не понимаю.

**Comment by pafnuty** [comment]
@makey2 
На странице с примерами есть несколько готовых решений, вы можете выбрать одно из трёх:

1. http://bp.pafnuty.name/examples/#5b92de857c847c7bdefb
2. http://bp.pafnuty.name/examples/#c71c73f00eaa478525fd (думаю это как раз то, что вам нужно)
3. http://bp.pafnuty.name/examples/#5d4f2316db3e7cebd1dcf0585eba65eb

Или на их основе сделать своё.
