### ISSUE TITLE
Не работает ссылка добавить в избранное.

### ISSUE THREAD

**Issue by monachddg** [dle-modules/DLE-BlockPro#165]
Добрый день!
Вывелт ссылку-картинку для добавления новости в избранное.
{$el.favorites}, но кнопка не работает. Вообще ничего не происходит.
Я уже кеш чистил, даже выключал и включал очистку кеша, бесполезно.
Кнопка не обновляется при нажатии, и при обновлении страницы тоже.
- Версия DLE: последняя

**Comment by pafnuty** [comment]
@monachddg Исправлено
