### ISSUE TITLE
Сортировка новостей из нескольких пунктов

### ISSUE THREAD

**Issue by monachddg** [dle-modules/DLE-BlockPro#169]
Здравствуйте!
Скажите, можно ли использовать фильтр\сортировку новостей как стандартыми средствами движка используя {sort}? 
Не смог найти  каким образом можно сделать сортировку по выбору из нескольких вариантов.
Подскажите, пожалуйста, как можно реализовать.
Спасибо заранее!

**Comment by pafnuty** [comment]
@monachddg Пользовательская сортировка новостей в модуле отсутствует и в ближайшее время её так же не планируется вводить.
