### ISSUE TITLE
Сортировка по новому типу дополнительного поля "дата" в режиме афиши

### ISSUE THREAD

**Issue by Jey-Shock** [dle-modules/DLE-BlockPro#170]
# Описание ошибки:

Релизована ли возможность сортировки по новому типу дополнительного поля "дата" в режиме афиши?
- Версия DLE: 14.0
- Версия PHP: 7.2

**Comment by pafnuty** [comment]
@Jey-Shock ничего специального для этого не делалось. Сортировка должна работать так же как и для других допполей.
