### ISSUE TITLE
Как установить 6.0.2 как плагин?

### ISSUE THREAD

**Issue by ballios** [dle-modules/DLE-BlockPro#171]
# Описание ошибки:

- Загрузка плагина на сайт через Админку ( раздел: Управление плагинами )
- Версия DLE: 14.0
- Версия PHP: 7.3.15

Загружаю - blockpro_plugin.zip - в этом разделе, но получаю невозможность:

"DataLife Engine не имеет прав доступа на некоторые папки. Поэтому вы можете задать FTP доступ для записи в них файлов. Ваш FTP доступ не будет сохранен на сервере. И по окончании использования данного доступа, он будет автоматически удален."

Получаю ошибку при вводе данных FTP:
- Невозможно соединиться с сервером!

Ввожу данные FTP, но ничего не получается, ошибка!
Как правильно заполнять - FTP доступ ?
Как установить плагин?

**Comment by pafnuty** [comment]
@ballios zip архив нужно загружать через форму добавления плагина на сайт 
![image](https://user-images.githubusercontent.com/1635679/81587929-ca992d80-93c8-11ea-9620-6447ab332b8e.png)
