### ISSUE TITLE
Галерея при добавлении описания не работает

### ISSUE THREAD

**Issue by makey2** [dle-modules/DLE-BlockPro#172]
Если к загруженным картинкам дополнительного поля "Галерея" внести описания, то они перестают выводиться.

Версия DataLife Engine: | 14.0
Версия PHP: | 7.1.33 
Для вывода использован пример http://bp.pafnuty.name/examples/#5d4f2316db3e7cebd1dcf0585eba65eb

в БД добавляется описание с разделителем `&#124;`  Пример: " `описание&#124;2020-03/photo.jpg` ".

**Comment by pafnuty** [comment]
@makey2 попробуйте так:
```
{set $arImage = $image|split:'&#124;'}
{set $strImage = $arImage[1] || $arImage[0]}
{set $imageTag}
				<img src="/uploads/posts/{$strImage}">
			{/set}
```
