### ISSUE TITLE
вопрос по AJAX навигация 

### ISSUE THREAD

**Issue by be2clack** [dle-modules/DLE-BlockPro#174]
Здравствуйте, сделал ajax навигация  на сайте, есть такая проблема, вывод идет списком на 30 новостей, когда через мобильный листаешь вниз и нажимаешь на след страницу по ajax все правильно работает и грузит новую страницу, но проблема в том что пользователь остается внизу так же.

Как сделать при переходе на новую страницу чтоб автоматом поднимался на начало ? на вверх ? а то не удобно листать вверх и вниз обратно

**Comment by pafnuty** [comment]
@be2clack после это строки:
https://github.com/dle-modules/DLE-BlockPro/blob/1542ee626f7b46a10b810a72b66d6ba85e8ac57b/templates/%7BTHEME%7D/blockpro/js/blockpro.js#L23
вы можете дописать вызов функции, которая делает скролл к нужному элементу.

**Comment by be2clack** [comment]
> @be2clack после это строки:
> https://github.com/dle-modules/DLE-BlockPro/blob/1542ee626f7b46a10b810a72b66d6ba85e8ac57b/templates/%7BTHEME%7D/blockpro/js/blockpro.js#L23
> 
> 
> вы можете дописать вызов функции, которая делает скролл к нужному элементу.

Можете мне сделать пример функции вызова? спасибо

**Comment by be2clack** [comment]
Ну или возможно ли сделать подгрузки новой страницы по кнопке "еще новости" например или авто подгрузки новостей когда через мобильный листаешь вниз ?

**Comment by pafnuty** [comment]
@be2clack 
Допустим функция, которая отвечает за прокрутку страницы к нужному элементу у вас называется так: 
```javascript
const scrollTo = (element) => {...}
```
Вызвать её можно так:
```javascript
scrollTo($block)
```

> Ну или возможно ли сделать подгрузки новой страницы по кнопке "еще новости" например или авто подгрузки новостей когда через мобильный листаешь вниз ?
Да, возможно, для этого нужно поймать событие, когда пользователь проскроллит до нужного места и загрузить следующую страницу.

**Comment by be2clack** [comment]
@pafnuty 
Вы можете сделать полный рабочий пример для тех кто не понимает в JS.
Вариант для скролла в начало, послсе перехода на страницу и пример подгрузки новой страницы когда скролишь вниз как на фб, твиттере. 

Оплачу. Спасибо

**Comment by be2clack** [comment]
@pafnuty думал наоборот все дома сидят и нечем заняться многим ) просто как бы продлили все это дело, и может затянутся на месяцы это пандемия. Сейчас никак не получится? думаю вы хорошо знакомы с js и вашим кодом у вас уйдет максимум час времени.
спасибо

**Comment by be2clack** [comment]
кто может сделать автозагрузку статьей ? по кнопке "Загрузить еще" оплачу

**Comment by pafnuty** [comment]
@be2clack карантин будет длиться ещё долго, поэтому вы можете самостоятельно найти нужное решение.

**Comment by be2clack** [comment]
@pafnuty ну я тут вот пытаюсь найти человека. и вообще как карантин мешает это реализовать ? я бы оплатил если вы сделали бы или компа с интернетом дома нету?

**Comment by pafnuty** [comment]
@be2clack карантин мешает напрямую - увеличивается количество работы, и работать весь день из дома, а потом делать ещё что, то, что не интересно и достаточно легко освоить любому новичку, ну совсем не хочется, а брать деньги за такое - совесть не позволяет.

**Comment by be2clack** [comment]
@pafnuty ну вы думаю если это легко, могли бы сделать пока писали этот комментарий) был бы рад. спасибо

**Comment by pafnuty** [comment]
Вот пример:
```
$('html, body').animate({
                    scrollTop: $block.offset().top
                }, 2000);
```

**Comment by be2clack** [comment]
сделайте уже официальную поддержку AJAX подгрузку новостей как комменты дле, как в соц сетях вк, фб, с двуями режимами, по кнопке и по скроллу

**Comment by pafnuty** [comment]
@be2clack если сделать, то найдётся сразу несколько человек, которым не понравится или не понадобится.
На всех угодить нельзя, но вполне вероятно, что как нибудь сделаю.

**Comment by be2clack** [comment]
@pafnuty там же по выбору будет, кто хочет пусть включить и тд, я оплачу сделайте по раньше а не как нибудь
