### ISSUE TITLE
Параметр this для значения доп поля

### ISSUE THREAD

**Issue by shadowiq4410** [dle-modules/DLE-BlockPro#175]
Сделайте возможно для перменной **xfSearch** указывать вместо value (значения поля) параметр **this**. 
**Например:** Есть доп поле Исполнитель, в полной новости оно имеет значение АК47, нужно вывести блок со всеми новостями от исполнителя из просматриваемой новости (все новости АК47).

**Comment by pafnuty** [comment]
"вы можете указать нужное значение допполя в строке подключения примерно так:
```
&xfSearch=xfName|[xf_name]
```
