### ISSUE TITLE
Мобильный шаблон (папка smartphone) берет шаблоны blockpro все только из основного шаблона

### ISSUE THREAD

**Issue by be2clack** [dle-modules/DLE-BlockPro#176]
или так задумано изначально? 
если так задумано, как сделать чтоб шаблоны blockpro брал с папки выбранного шаблона
и еще вопрос, как использовать в блок про теги из dle

{fullimage-x} | Выводит URL картинки, находящийся в тексте полной новости, где "x" это номер картинки в новости
[fullimage-x] текст [/fullimage-x]

**Comment by be2clack** [comment]
Еще вопрос, если выбрано несколько категорий. как вывести только одну первую категорию ?

**Comment by pafnuty** [comment]
@be2clack Исправлено, можно проверять.

**Comment by pafnuty** [comment]
> как использовать в блок про теги из dle

Теги DLE в модуле не работают.
Для вывода картинки используйте модификатор [image](http://bp.pafnuty.name/documentation/#mod-image)

Для вывода информации о категории есть модификатор [catinfo](http://bp.pafnuty.name/documentation/#mod-catinfo)
