### ISSUE TITLE
Выводятся комментарии находящиеся на предмодерации

### ISSUE THREAD

**Issue by Andreikoa** [dle-modules/DLE-BlockPro#183]
# Описание "ошибки":

На странице выводятся комментарии которые находятся на предмодерации и еще не одобрены админом для публикации.

##Строка подключения
{include '/blockpro/bp_comments.tpl' postId=$el.id limit=0}

## Код используемого шаблона:
{if $postId > 0}
{set $commentsLimit = ($limit > 0) ? $limit*1 : 900 }
{set $comments = $.blockPro->db->getAll('SELECT * FROM ?n WHERE post_id=?i LIMIT 0, ?p', 'dle_comments', $postId, $commentsLimit)}
<div>
   <div>Комментарии:</div>
   {foreach $comments as $comment index = $index}
   {set $i = $index + 1 + $delta}
   <div class="foim">
      <div class="letter colo{$i}">{$comment.autor|limit:'2':''}</div>
      <span class="fname">{$comment.autor}</span>
   </div>
   <p>
      {$comment.text}
      <span class="datco">{$comment.date|dateformat:"Y m d"}</span>
   </p>
   {foreachelse}
   {/foreach}
</div>
{else}
{/if}

**Comment by pafnuty** [comment]
@Andreikoa 
```smarty
{set $comments = $.blockPro->db->getAll('SELECT * FROM ?n WHERE post_id=?i AND approve=?i LIMIT 0, ?p', 'dle_comments', $postId, 1, $commentsLimit)}
```
что-то типа такого попробуйте. нужно просто отфильтровать лишнее.

**Comment by Andreikoa** [comment]
Спасибо большое за помощь. Теперь комментарий выводится только после одобрения админом.

**Comment by Andreikoa** [comment]
Спасибо большое за помощь. Теперь комментарий выводится только после одобрения админом.
