### ISSUE TITLE
Как правильно обновиться

### ISSUE THREAD

**Issue by Yuribtr** [dle-modules/DLE-BlockPro#186]
Здравствуйте,
подскажите пожалуйста, как правильнее обновиться с версии 5.0.2 до последней 6.0.3?
Я заменил файлы модуля в папке engine но мне выдало фатальные ошибки. Как я понимаю надо еще строки подключения в шаблонах менять? Спасибо.
Версия DLE 13.0, но хочу обновить до 14.1, в связи с чем сначала и пытаюсь обновить BlockPro

Также прошу уточнить, будет ли работать ваш плагин с MySQL версии 8 ? Там вроде бы поменялись регулярки.

**Comment by pafnuty** [comment]
@Yuribtr 
Для обновления удалите существующий модуль, все файлы и сохраните резервные копии файлов шаблонов.
Далее установите модуль как плагин, залейте обратно сохранённые шаблоны.
Всё это делать конечно же производить лучше локально на копии сайта.

По поводу mysql 8 подсказать не могу, если будут ошибки, сообщите, постараемся исправить.

**Comment by Yuribtr** [comment]
@pafnuty 
Спасибо большое. Получается что строки подключения должны остаться прежние, это радует )))
А вот по совместимости с 8-й версией новости грустные:

```
> Fatal error: Uncaught Exception: SafeMySQL: Illegal argument to a regular expression.. Full query: [SELECT p.id, p.autor, p.date, p.short_story, p.full_story, p.xfields, p.title, p.category, p.alt_name, p.allow_comm, p.comm_num, p.fixed, p.allow_main, p.symbol, p.tags, e.news_read, e.allow_rate, e.rating, e.vote_num, e.votes, e.related_ids, e.view_edit, e.editdate, e.editor, e.reason FROM `dle_post` p LEFT JOIN `dle_post_extras` e ON (p.id=e.news_id) WHERE approve AND category regexp "[[:<:]](47)[[:>:]]" AND p.date < "2020-10-08 23:16:14" ORDER BY fixed DESC, p.date DESC LIMIT 0, 2] in /var/www/mysite/engine/modules/base/core/SafeMySQL.php:632 Stack trace: #0 /var/www/mysite/engine/modules/base/core/SafeMySQL.php(492): SafeMySQL->error('SafeMySQL: Ille...') #1 /var/www/mysite/engine/modules/base/core/SafeMySQL.php(291): SafeMySQL->rawQuery('SELECT p.id, p....') #2 /var/www/mysite/engine/modules/base/blockpro.php(958): SafeMySQL->getAll('SELECT ? in /var/www/mysite/engine/modules/base/core/SafeMySQL.php on line 632
```

**Comment by pafnuty** [comment]
на сайте mysql написано https://dev.mysql.com/doc/refman/8.0/en/regexp.html#regexp-syntax
что 
> The Spencer library supports word-beginning and word-end boundary markers ([[:<:]] and [[:>:]] notation). ICU does not. For ICU, you can use \b to match word boundaries; double the backslash because MySQL interprets it as the escape character within strings.

Получается, что в коде все вхождения старой нотации регулярок нужно заменить на новые.

Попробуйте этот плагин поставить: [blockpromodifier-mysql-8-patch.zip](https://github.com/dle-modules/DLE-BlockPro/files/5366842/blockpromodifier-mysql-8-patch.zip)

**Comment by Yuribtr** [comment]
Спасибо! Сделаю когда буду апгрейдить систему, потом отпишусь

**Comment by dj-avtosh** [comment]
`AND category REGEXP "([[:punct:]]|^)(47)([[:punct:]]|$)"`

или так

**Comment by Yuribtr** [comment]
@pafnuty к сожалению ваш плагин не сработал на MySQL 8.0.21, но я в него внес правки как написал @dj-avtosh (спасибо ему огромное) и все заработало!
Так что можете опубликовать плагин с этим содержимым:

```xml
<?xml version="1.0" encoding="utf-8"?>
<dleplugin>
	<name>BlockProModifier MySQL 8 patch</name>
	<description>Плагин для BlockPro, исправляющий ошибки на MySQL 8</description>
	<icon>engine/skins/images/blockpro.png</icon>
	<version>1.0.0</version>
	<dleversion>14</dleversion>
	<versioncompare>greater</versioncompare>
	<upgradeurl></upgradeurl>
	<filedelete>0</filedelete>
	<needplugin>BlockPro</needplugin>
	<mnotice>0</mnotice>
	<mysqlinstall><![CDATA[]]></mysqlinstall>
	<mysqlupgrade><![CDATA[]]></mysqlupgrade>
	<mysqlenable><![CDATA[]]></mysqlenable>
	<mysqldisable><![CDATA[]]></mysqldisable>
	<mysqldelete><![CDATA[]]></mysqldelete>
	<phpinstall><![CDATA[]]></phpinstall>
	<phpupgrade><![CDATA[]]></phpupgrade>
	<phpenable><![CDATA[]]></phpenable>
	<phpdisable><![CDATA[]]></phpdisable>
	<phpdelete><![CDATA[]]></phpdelete>
	<notice><![CDATA[]]></notice>
	<file name="engine/modules/base/blockpro.inc.php">
		<operation action="replace">
			<searchcode><![CDATA[[[:<:]]]]></searchcode>
			<replacecode><![CDATA[([[:punct:]]|^)]]></replacecode>
		</operation>
		<operation action="replace">
			<searchcode><![CDATA[[[:>:]]]]></searchcode>
			<replacecode><![CDATA[([[:punct:]]|$)]]></replacecode>
		</operation>
	</file>
</dleplugin>
```
