### ISSUE TITLE
Как можно поправить page/2/page/2/

### ISSUE THREAD

**Issue by maksisru** [dle-modules/DLE-BlockPro#188]
Как можно поправить page/2/page/2/  ?

если галочки нет (Отслеживать стандартную навигацию dle) то  без перезагрузки страницы новость все ок показывает следующую. `{include file="engine/modules/base/blockpro.php?startFrom=1&limit=1&&symbols=atg&sort=none&order=asis&sort=none&order=asis&showNav=y&pageNum=[xfvalue_sort]&navStyle=arrows"}
`

когда в настройках стоит  галочка _(&navDefaultGet=y)_ Отслеживать стандартную навигацию dle  (то при нажатии на далее, **не переходит** а в адресе выдает page/2/ ) КАК СДЕЛАТЬ  чтоб **переходило** на след новость?
https://prnt.sc/vhrs7c в  настройках dle  ЧПУ: Включено',nТип ЧПУ:Тип 2 на ЧПУ:Тип 3 также
https://prnt.sc/vhrtrm в настройках dle  ЧПУ: Включено',nТип ЧПУ:Тип 1

https://prnt.sc/vhrv88  ЧПУ: ВЫКЛЮЧЕНО

`{include file="engine/modules/base/blockpro.php?startFrom=1&limit=1&&symbols=atg&sort=none&order=asis&sort=none&order=asis&showNav=y&pageNum=[xfvalue_sort]&navStyle=arrows&navDefaultGet=y"}
`

мне для проекта надо с перезагрузкой ... даже не знаю где смотреть уже(( как поправить.

**Comment by pafnuty** [comment]
@maksisru в полной новости это не работает.
Суть настройки в том, что бы выдавать вторую страницу новостей, если пользователь находится на ней.
Она нужна на случай, когда необходимо заменить вывод стандартных новостей на blockpro. Кстати, для этого даже лучше подойдёт [blockProLight](https://github.com/dle-modules/DLE-BlockProLight)

**Comment by maksisru** [comment]
спасибо
