### ISSUE TITLE
Как мне перенести лицензию на другой домен?

### ISSUE THREAD

**Issue by stopani** [dle-modules/DLE-BlockPro#195]
- Версия DLE: 10.1
- Версия PHP: 5.6

BlockPro (4.8.1)
Мне не подходят новые версии скрипта.
Как мне перенести версию 4.8.1 на другой домен?

**Comment by pafnuty** [comment]
https://github.com/dle-modules/DLE-BlockPro/releases/tag/v4.8.1
скачайте исходный код, он не зашифрован.
